# Generated by Django 5.1.6 on 2025-02-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('work_format', models.CharField(max_length=100)),
                ('ready_for_business_trips', models.CharField(max_length=100)),
                ('expected_salary', models.IntegerField()),
                ('experience', models.CharField(max_length=255)),
                ('photo', models.URLField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('about', models.TextField(blank=True)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
