# Generated by Django 5.1.6 on 2025-02-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('hiring_plan', models.IntegerField()),
                ('work_format', models.CharField(max_length=100)),
                ('salary_min', models.IntegerField(blank=True, null=True)),
                ('salary_max', models.IntegerField(blank=True, null=True)),
                ('experience', models.CharField(max_length=255)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('job_description', models.TextField()),
                ('responsibilities', models.JSONField(blank=True, default=list)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('conditions', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
